{% set name = "formulaic" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6eb65bedd1903c5381d8f2ae7a55b6ba13cb77d57bbaf6e4278f3b2c38e3660e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.2
    - pip
    - hatch
    - hatch-vcs
  run:
    - python >=3.7.2
    - astor >=0.8
    - cached_property
    - graphlib-backport
    - interface_meta >=1.2
    - numpy >=1.16.5
    - pandas >=1.0
    - scipy >=1.6
    - typing-extensions >=4.2
    - wrapt >=1.0
  run_constrained:
    - pyarrow >=1
    - sympy >=1.3,!=1.10

test:
  imports:
    - formulaic

about:
  home: https://github.com/matthewwardrop/formulaic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance implementation of Wilkinson formulas for Python.
  description: |
    Formulaic is a high-performance implementation of Wilkinson formulas for Python.
  doc_url: https://matthewwardrop.github.io/formulaic
  dev_url: https://github.com/matthewwardrop/formulaic

extra:
  recipe-maintainers:
    - matthewwardrop
