{% set name = "formulaic" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ddf80e4bef976dd99698aa27512015276c7b86c314b601ae6fd360c7741b7231

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - astor >=0.8
    - cached_property
    - graphlib-backport
    - interface_meta >=1.2
    - numpy >=1.16.5
    - pandas >=1.0
    - scipy >=1.6
    - typing-extensions >=4.2
    - wrapt >=1.0
  run_constrained:
    - pyarrow >=1
    - sympy >=1.3,!=1.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - formulaic

about:
  home: https://github.com/matthewwardrop/formulaic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance implementation of Wilkinson formulas for Python.
  description: |
    Formulaic is a high-performance implementation of Wilkinson formulas for Python.
  doc_url: https://matthewwardrop.github.io/formulaic
  dev_url: https://github.com/matthewwardrop/formulaic

extra:
  recipe-maintainers:
    - matthewwardrop
