{% set name = "formulaic" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e16262562147acbdeda1178d778ac189a93bd63e2348261bd8b5d303f173f6d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.7
    - pip
    - setuptools
    - setupmeta
  host:
    - python >=3.7
    - pip
    - setuptools
    - setupmeta
  run:
    - python >=3.7
    - astor >=0.7
    - interface_meta >=1.2
    - numpy >=1.3
    - pandas >=1.2
    - scipy >=1.6
    - wrapt >=1.0
  run_constrained:
    - pyarrow >=1
    - sympy >=1.3,<1.10

test:
  imports:
    - formulaic

about:
  home: https://github.com/matthewwardrop/formulaic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance implementation of Wilkinson formulas for Python.
  description: |
    Formulaic is a high-performance implementation of Wilkinson formulas for Python.
  doc_url: https://matthewwardrop.github.io/formulaic
  dev_url: https://github.com/matthewwardrop/formulaic

extra:
  recipe-maintainers:
    - matthewwardrop
