{% set name = "formulaic" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab5c43a5b107d1b1e87f55cf0a01245531cce793d3dcab433dae12053c3cb2d6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - interface_meta >=1.2
    - narwhals >=1.17
    - numpy >=1.20
    - pandas >=1.3
    - scipy >=1.6
    - typing-extensions >=4.2
    - wrapt >=1.0  # [py < 313]
    - wrapt >=1.17  # [py >= 313]
    - typing-extensions >=4.2
  run_constrained:
    - polars >=1
    - pyarrow >=1
    - sympy >=1.3,!=1.10

test:
  requires:
    - python {{ python_min }}
    - polars
    - pyarrow
    - sympy
  imports:
    - formulaic

about:
  home: https://github.com/matthewwardrop/formulaic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance implementation of Wilkinson formulas for Python.
  description: |
    Formulaic is a high-performance implementation of Wilkinson formulas for Python.
  doc_url: https://matthewwardrop.github.io/formulaic
  dev_url: https://github.com/matthewwardrop/formulaic

extra:
  recipe-maintainers:
    - matthewwardrop
